### ISSUE TITLE
Exception When clicking an element during layout editing

### ISSUE THREAD

**Issue by andwah** [Polyjuice/Launcher#94]
I have the Launcher, SignInApp and UserAdminApp running.
I click "System User Groups" in the left menu. and i click on a system user group.

 then i click the "gear" icon and click on the "Close" button element.

```
Exception caught during observer callback: TypeError: Cannot read property 'querySelector' of undefined
    at juicy-tile-tree.Polymer.toDisplayName (http://localhost:8080/vendor/juicy-tile-editor/src/juicy-tile-tree.js:17:28)
    at Object.g.transform (http://localhost:8080/vendor/polymer/polymer.js:12:1182)
    at Object.l.getValue (http://localhost:8080/vendor/polymer/polymer.js:12:4125)
    at Object.l.getBinding (http://localhost:8080/vendor/polymer/polymer.js:12:3948)
    at http://localhost:8080/vendor/polymer/polymer.js:11:30003
    at u (http://localhost:8080/vendor/polymer/polymer.js:13:1060)
    at v (http://localhost:8080/vendor/polymer/polymer.js:13:1235)
    at w (http://localhost:8080/vendor/polymer/polymer.js:13:1552)
    at A (http://localhost:8080/vendor/polymer/polymer.js:13:2497)
    at A (http://localhost:8080/vendor/polymer/polymer.js:13:2388) 
```

**Comment by miyconst** [comment]
@andwah can this issue be closed?

**Comment by warpech** [comment]
Closing as non-reproducible anymore, fixed with other fixes.
